refractor files & improved helper scripts

diff --git a/scripts/dbimport b/scripts/dbimport
--- a/scripts/dbimport
+++ b/scripts/dbimport
@@ -51,49 +51,51 @@ function updateMagentoEnvAndCompile(){
   echo "password: Test1234"
   echo -e "\n"
 
-  read -p "Would you like to Update Web URL's in New DB? (y or n): " -n 1 -r
-  if [[ $REPLY =~ ^[Yy]$ ]]
-  then
-    function getURLFromDB(){
-      DB_RESULT=$(docker exec -i "$CONTAINER_DB" mysql -uroot -proot $DB_NAME -e "select distinct(value) from core_config_data where path like 'web/%secure%' and value is not null")
-      URL_ARR=( $( for i in $DB_RESULT ; do echo $i ; done ) )
-      COUNT=${#URL_ARR[@]}
-      for ((i=1;i<COUNT;i++))
-          do echo "${i}: ${URL_ARR[$i]}"
-        done
-        echo "q: Quit"
-    }
-
-    $(clear >&2)
-    while true
-    do
-        getURLFromDB
-        read -p 'Select the URL you would like to update? ' URL_INDEX
-
-        if [[ $URL_INDEX == "q" ]]; then
-          break
-        fi
-
-        if [ "${URL_ARR[URL_INDEX]+abc}" ]; then
-          echo 'Enter "q" to go back to Main Menu';
-          read -p "Please Enter the Url to replace ${URL_ARR[URL_INDEX]}: " SITE_URL
-          if [[ $SITE_URL != "q" ]]; then
-            docker exec -i "$CONTAINER_DB" mysql -uroot -proot $DB_NAME -e "UPDATE core_config_data SET value = CONCAT('${SITE_URL}','/') WHERE value = '${URL_ARR[URL_INDEX]}'"
-            echo "--------------- Url Updated --------------"
-          fi
-        else
-          echo "Invalid Input!"
-        fi
-    done
-  fi
-
     echo '-------------- Clearing Cache ------------'
     docker exec -i --user www-data "$CONTAINER_WEB" bin/magento cache:flush
 
     echo '----------- Reindexing Magento -----------'
-    docker exec -i --user www-data "$CONTAINER_WEB" bin/magento cache:flush
+    docker exec -i --user www-data "$CONTAINER_WEB" bin/magento indexer:reindex
 
     echo "----- Magento is now using: ${DB_NAME}"
+}
+
+function updateUrls(){
+  read -p "Would you like to Update Web URL's in New DB? (y or n): " -n 1 -r
+    if [[ $REPLY =~ ^[Yy]$ ]]
+    then
+      function getURLFromDB(){
+        DB_RESULT=$(docker exec -i "$CONTAINER_DB" mysql -uroot -proot $DB_NAME -e "select distinct(value) from core_config_data where path like 'web/%secure%' and value is not null")
+        URL_ARR=( $( for i in $DB_RESULT ; do echo $i ; done ) )
+        COUNT=${#URL_ARR[@]}
+        for ((i=1;i<COUNT;i++))
+            do echo "${i}: ${URL_ARR[$i]}"
+          done
+          echo "q: Quit"
+      }
+
+      $(clear >&2)
+      while true
+      do
+          getURLFromDB
+          read -p 'Select the URL you would like to update? ' URL_INDEX
+
+          if [[ $URL_INDEX == "q" ]]; then
+            break
+          fi
+
+          if [ "${URL_ARR[URL_INDEX]+abc}" ]; then
+            echo 'Enter "q" to go back to Main Menu';
+            read -p "Please Enter the Url to replace ${URL_ARR[URL_INDEX]}: " SITE_URL
+            if [[ $SITE_URL != "q" ]]; then
+              docker exec -i "$CONTAINER_DB" mysql -uroot -proot $DB_NAME -e "UPDATE core_config_data SET value = CONCAT('${SITE_URL}','/') WHERE value = '${URL_ARR[URL_INDEX]}'"
+              echo "--------------- Url Updated --------------"
+            fi
+          else
+            echo "Invalid Input!"
+          fi
+      done
+    fi
 }
 
 # DATABASE IMPORT
@@ -104,6 +106,9 @@ docker exec -i "$CONTAINER_DB" mysql -uroot -proot $DB_NAME < db.sql &
 piddbimport=$!
 showSpinner "$piddbimport"
 echo "----------- Database Imported! -----------"
+
+updateUrls $CONTAINER_DB
+echo -e "\n"
 
 read -p "Update Magento to use the new Database? (y or n): " -n 1 -r
 echo    # (optional) move to a new line
